"""Support incremental session summary

Revision ID: 51702f946b30
Revises: ee119aa0cc9f
Create Date: 2026-06-29 11:25:30.937039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51702f946b30'
down_revision: Union[str, Sequence[str], None] = 'ee119aa0cc9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('summary_token_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('chat_sessions', sa.Column('summary_message_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'summary_message_count')
    op.drop_column('chat_sessions', 'summary_token_count')
    # ### end Alembic commands ###
