"""update_memory_vector_and_profile

Revision ID: 1f825ad30e0c
Revises: 9d6d085ab9fb
Create Date: 2026-04-19 15:06:55.406420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f825ad30e0c'
down_revision: Union[str, Sequence[str], None] = '9d6d085ab9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_vectors', sa.Column('client_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_memory_vectors_client_id'), 'memory_vectors', ['client_id'], unique=False)
    op.create_foreign_key(None, 'memory_vectors', 'client_profiles', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memory_vectors', type_='foreignkey')
    op.drop_index(op.f('ix_memory_vectors_client_id'), table_name='memory_vectors')
    op.drop_column('memory_vectors', 'client_id')
    # ### end Alembic commands ###
