"""update_memory_vector_and_profile

Revision ID: 316f7f6c58bc
Revises: 1f825ad30e0c
Create Date: 2026-04-21 13:33:51.355876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316f7f6c58bc'
down_revision: Union[str, Sequence[str], None] = '1f825ad30e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
